services:
  database:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - ./packages/database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "${API_PORT:-3001}:3001"
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - database

volumes:
  postgres_data: