name: "Test and Report Coverage on PRs"
on:
  pull_request:
    branches:
      - trunk
      - "!weblate"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.10.0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.4

      - name: Install dependencies
        run: pnpm install

      - name: "Test"
        run: pnpm test:coverage

      - name: "Report API coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "API"
          vite-config-path: "./apps/api/vitest.config.ts"
          json-summary-path: "./apps/api/tests/coverage/coverage-summary.json"
          json-final-path: "./apps/api/tests/coverage/coverage-final.json"

      - name: "Report Core coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Core"
          vite-config-path: "./packages/core/vitest.config.ts"
          json-summary-path: "./packages/core/tests/coverage/coverage-summary.json"
          json-final-path: "./packages/core/tests/coverage/coverage-final.json"
